// Minimal catalog used as a fallback when Supabase tables are not present
/** @type {Array<{id:string,title:string,category:string,difficulty:1|2|3,estimatedMinutes:number,totalLessons:number,xpReward:number,description:string,tags:string[],videoUrl:string,thumbnail:string, role:"Data Scientist"|"Business Analyst"}>} */
const defaultModules = [
  // Data Scientist
  { id: "ds-python-101", title: "Python Basics", category: "Programming Skills (DS)", difficulty: 1, estimatedMinutes: 35, totalLessons: 6, xpReward: 120, description: "Syntax, variables, control flow, functions, and data structures.", tags: ["Python","Beginner","Programming"], videoUrl: "https://www.youtube.com/embed/_uQrJ0TkZlc", thumbnail: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Data Scientist" },
  { id: "ds-python-201", title: "Python for Data (Pandas/Numpy)", category: "Programming Skills (DS)", difficulty: 2, estimatedMinutes: 50, totalLessons: 8, xpReward: 160, description: "Pandas, NumPy, cleaning data, transforms, basic viz.", tags: ["Python","Pandas","NumPy"], videoUrl: "https://www.youtube.com/embed/vmEHCJofslg", thumbnail: "https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Data Scientist" },
  { id: "ds-sql-101", title: "SQL for Analytics", category: "Programming Skills (DS)", difficulty: 2, estimatedMinutes: 40, totalLessons: 7, xpReward: 150, description: "SELECT, JOIN, GROUP BY, window functions.", tags: ["SQL","Analytics","Databases"], videoUrl: "https://www.youtube.com/embed/HXV3zeQKqGY", thumbnail: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Data Scientist" },
  { id: "ds-ml-101", title: "ML Basics (Scikit-learn)", category: "Technical Skills (DS)", difficulty: 2, estimatedMinutes: 60, totalLessons: 9, xpReward: 200, description: "Train/test split, baseline models, evaluation.", tags: ["ML","scikit-learn","Evaluation"], videoUrl: "https://www.youtube.com/embed/0Lt9w-BxKFQ", thumbnail: "https://images.pexels.com/photos/373076/pexels-photo-373076.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Data Scientist" },
  { id: "ds-ml-202", title: "Model Evaluation & Metrics", category: "Technical Skills (DS)", difficulty: 2, estimatedMinutes: 55, totalLessons: 7, xpReward: 180, description: "ROC-AUC, PR curves, calibration, error analysis.", tags: ["ML","Metrics","Evaluation"], videoUrl: "https://www.youtube.com/embed/85dtiMz9tSo", thumbnail: "https://images.pexels.com/photos/669623/pexels-photo-669623.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Data Scientist" },
  { id: "ds-ml-203", title: "Tree-Based Models (XGBoost)", category: "Technical Skills (DS)", difficulty: 2, estimatedMinutes: 60, totalLessons: 8, xpReward: 200, description: "Boosting, tuning, feature importance, pitfalls.", tags: ["XGBoost","Trees","Tuning"], videoUrl: "https://www.youtube.com/embed/OzZ7E2yZ0bU", thumbnail: "https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Data Scientist" },
  { id: "ds-ml-301", title: "Neural Nets Basics (Keras)", category: "Technical Skills (DS)", difficulty: 3, estimatedMinutes: 70, totalLessons: 9, xpReward: 240, description: "Dense nets, activations, loss, overfitting.", tags: ["Deep Learning","Keras","NN"], videoUrl: "https://www.youtube.com/embed/wQ8BIBpya2k", thumbnail: "https://images.pexels.com/photos/1181316/pexels-photo-1181316.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Data Scientist" },
  { id: "ds-sql-201", title: "Advanced SQL for DS", category: "Programming Skills (DS)", difficulty: 2, estimatedMinutes: 55, totalLessons: 8, xpReward: 180, description: "CTEs, window funcs, optimization, anti-joins.", tags: ["SQL","Advanced","CTE"], videoUrl: "https://www.youtube.com/embed/7S_tz1z_5bA", thumbnail: "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Data Scientist" },
  { id: "ds-prod-101", title: "ML in Production Basics", category: "Technical Skills (DS)", difficulty: 2, estimatedMinutes: 45, totalLessons: 6, xpReward: 150, description: "Data drift, monitoring, versioning, pipelines.", tags: ["MLOps","Production","Monitoring"], videoUrl: "https://www.youtube.com/embed/cH-5J3N1s2Q", thumbnail: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Data Scientist" },
  // Business Analyst
  { id: "ba-excel-101", title: "Excel for Analysis", category: "Programming/Tools (BA)", difficulty: 1, estimatedMinutes: 30, totalLessons: 5, xpReward: 100, description: "Formulas, pivot tables, charts, cleaning data.", tags: ["Excel","Spreadsheets","Charts"], videoUrl: "https://www.youtube.com/embed/rwbho0CgEAE", thumbnail: "https://images.pexels.com/photos/669619/pexels-photo-669619.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-sql-101", title: "SQL Basics (BA)", category: "Programming/Tools (BA)", difficulty: 1, estimatedMinutes: 35, totalLessons: 6, xpReward: 120, description: "SELECT/WHERE/ORDER BY for business questions.", tags: ["SQL","Business","Data"], videoUrl: "https://www.youtube.com/embed/27axs9dO7AE", thumbnail: "https://images.pexels.com/photos/267614/pexels-photo-267614.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-bi-101", title: "BI Dashboards (Power BI/Looker)", category: "Programming/Tools (BA)", difficulty: 2, estimatedMinutes: 45, totalLessons: 7, xpReward: 150, description: "Metrics, visuals, filters, publishing basics.", tags: ["BI","Dashboards","PowerBI"], videoUrl: "https://www.youtube.com/embed/AGrl-H87pRU", thumbnail: "https://images.pexels.com/photos/6476584/pexels-photo-6476584.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-stats-101", title: "Business Stats Fundamentals", category: "Technical/Analytics (BA)", difficulty: 1, estimatedMinutes: 40, totalLessons: 6, xpReward: 130, description: "Descriptive stats, sampling, confidence.", tags: ["Statistics","Business"], videoUrl: "https://www.youtube.com/embed/r5iy-Sv1S7E", thumbnail: "https://images.pexels.com/photos/669616/pexels-photo-669616.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-abtest-101", title: "A/B Testing Basics", category: "Technical/Analytics (BA)", difficulty: 2, estimatedMinutes: 40, totalLessons: 7, xpReward: 150, description: "Test design, metrics, pitfalls, interpreting results.", tags: ["Experimentation","A/B Testing","Product"], videoUrl: "https://www.youtube.com/embed/0CpK4QW9DjI", thumbnail: "https://images.pexels.com/photos/669610/pexels-photo-669610.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-seg-201", title: "Segmentation & Cohorts", category: "Technical/Analytics (BA)", difficulty: 2, estimatedMinutes: 50, totalLessons: 8, xpReward: 160, description: "User segments, funnels, retention/cohorts.", tags: ["Segmentation","Cohorts","Funnels"], videoUrl: "https://www.youtube.com/embed/2oixYvNysZg", thumbnail: "https://images.pexels.com/photos/590020/pexels-photo-590020.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-comm-101", title: "Stakeholder Communication", category: "Communication/Business (BA)", difficulty: 1, estimatedMinutes: 30, totalLessons: 5, xpReward: 100, description: "Clear updates, risks, and decisions.", tags: ["Stakeholders","Communication"], videoUrl: "https://www.youtube.com/embed/Ad6Y9VvS5wQ", thumbnail: "https://images.pexels.com/photos/3183183/pexels-photo-3183183.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-comm-201", title: "Writing PRDs & Analyses", category: "Communication/Business (BA)", difficulty: 2, estimatedMinutes: 45, totalLessons: 7, xpReward: 150, description: "Problem, context, requirements, success metrics.", tags: ["PRD","Writing","Analysis"], videoUrl: "https://www.youtube.com/embed/8h5VnYxqX2w", thumbnail: "https://images.pexels.com/photos/6476588/pexels-photo-6476588.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-story-201", title: "Data Storytelling for Biz", category: "Communication/Business (BA)", difficulty: 2, estimatedMinutes: 40, totalLessons: 6, xpReward: 140, description: "Narratives, visuals, executive summaries.", tags: ["Storytelling","Business","Slides"], videoUrl: "https://www.youtube.com/embed/G8d3n9VBfWY", thumbnail: "https://images.pexels.com/photos/1181355/pexels-photo-1181355.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-sql-201", title: "Analyst SQL Patterns", category: "Programming/Tools (BA)", difficulty: 2, estimatedMinutes: 45, totalLessons: 7, xpReward: 150, description: "Cohorts, retention, percentiles, deduping.", tags: ["SQL","Analytics","Patterns"], videoUrl: "https://www.youtube.com/embed/7S_tz1z_5bA", thumbnail: "https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-bi-201", title: "Power BI Fundamentals", category: "Programming/Tools (BA)", difficulty: 2, estimatedMinutes: 50, totalLessons: 8, xpReward: 160, description: "Data model, DAX, visuals, publishing.", tags: ["Power BI","DAX","Dashboards"], videoUrl: "https://www.youtube.com/embed/AGrl-H87pRU", thumbnail: "https://images.pexels.com/photos/590020/pexels-photo-590020.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-look-201", title: "Looker Studio Dashboards", category: "Programming/Tools (BA)", difficulty: 2, estimatedMinutes: 40, totalLessons: 6, xpReward: 140, description: "Connectors, charts, filters, sharing.", tags: ["Looker","Dashboards","Viz"], videoUrl: "https://www.youtube.com/embed/5aH2Ppj6F5M", thumbnail: "https://images.pexels.com/photos/669615/pexels-photo-669615.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
  { id: "ba-comm-202", title: "Executive Summaries", category: "Communication/Business (BA)", difficulty: 2, estimatedMinutes: 35, totalLessons: 5, xpReward: 120, description: "Structure insights for leadership decisions.", tags: ["Executive","Communication","Strategy"], videoUrl: "https://www.youtube.com/embed/IJd3QzYVb6M", thumbnail: "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=400", role: "Business Analyst" },
];

module.exports = { defaultModules };


